In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
ds = sns.load_dataset('iris')
# sns.get_dataset_names()
# from sklearn.datasets import load_boston

In [2]:
ds

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
ds.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
ds.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [5]:
ds.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
ds['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
x = ds.drop('species',axis = 1)
y = ds['species']

In [8]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [9]:
ds['species'] = label.fit_transform(ds['species'])
ds.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
ds
ds['species'].value_counts()
print(ds.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [11]:
x = ds.drop('species',axis = 1)
y = ds['species']

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=43)

x_train.shape , x_test.shape , y_train.shape , y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
gnb = GaussianNB()

In [15]:
gnb.fit(x_train , y_train)
print(np.array(y_train))

[1 0 1 1 2 2 1 2 1 1 1 2 1 1 0 1 1 1 1 1 1 1 1 2 0 2 2 0 1 2 1 0 0 1 2 2 0
 0 0 0 0 1 2 1 2 2 2 2 0 1 0 0 2 0 0 1 0 1 2 0 0 2 0 2 2 2 1 2 2 0 2 2 1 2
 0 0 0 2 0 2 0 2 1 2 0 1 1 0 2 0 2 1 0 2 1 2 1 1 0 2 0 2 1 0 2 1 2 2 0 2 1
 2 1 1 0 1 0 0 1 1]


In [16]:
y_train_pred = gnb.predict(x_train)
print(np.array(y_train_pred))
# resetting the indices during concatenation is necessary
df_train = pd.concat([pd.Series(y_train).reset_index(drop=True), pd.Series(y_train_pred).reset_index(drop=True)],axis=1)
df_train.columns=['Training','Predicted']
df_train.head(10)

[1 0 1 1 2 2 1 2 1 1 1 2 1 2 0 1 1 1 1 1 1 1 1 2 0 1 2 0 1 2 1 0 0 1 2 2 0
 0 0 0 0 1 1 1 2 2 2 2 0 1 0 0 2 0 0 1 0 2 2 0 0 2 0 2 2 2 1 2 2 0 2 2 1 2
 0 0 0 2 0 2 0 2 1 2 0 1 1 0 2 0 2 1 0 1 1 2 1 1 0 2 0 2 1 0 2 1 2 2 0 2 1
 2 1 1 0 1 0 0 1 1]


Training  Predicted
0         1          1
1         0          0
2         1          1
3         1          1
4         2          2
5         2          2
6         1          1
7         2          2
8         1          1
9         1          1

In [17]:
y_test_pred = gnb.predict(x_test)
print(np.array(y_test_pred))

df_test = pd.concat([pd.Series(y_test).reset_index(drop=True),pd.Series(y_test_pred).reset_index(drop=True)],axis=1)
df_test.columns = ['Actual','Predicted']
df_test.head(10)

[0 0 2 1 2 0 2 1 1 1 0 1 2 0 1 1 0 0 2 2 0 0 0 1 2 2 0 1 0 0]


Actual  Predicted
0       0          0
1       0          0
2       2          2
3       1          1
4       2          2
5       0          0
6       2          2
7       1          1
8       1          1
9       1          1

In [18]:
print(gnb.classes_)

[0 1 2]


In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_test_pred)

In [20]:
print(cm)

[[13  0  0]
 [ 0  8  0]
 [ 0  1  8]]


In [21]:
from sklearn.metrics import recall_score , precision_score , f1_score , accuracy_score

pred_y = y_test_pred
test_y = y_test
recall = recall_score( test_y , pred_y , average=None )
print( recall )

precision = precision_score( test_y , pred_y , average=None)
print( precision )

accuracy = accuracy_score( test_y , pred_y)
print( accuracy )

f1 = f1_score( test_y , pred_y , average=None)
print( f1 )

[1.         1.         0.88888889]
[1.         0.88888889 1.        ]
0.9666666666666667
[1.         0.94117647 0.94117647]


In [27]:
tp = np.diag(cm)
fn = np.sum(cm, axis=1) - tp
fp = np.sum(cm, axis=0) - tp
tn = np.sum(cm) - (tp + fn + fp)

print(tp , fn , fp , tn)
tp1 = np.diag(cm)
fp1 = np.sum(cm,axis=0)-tp
fn1 = np.sum(cm,axis=1)-tp
tn1 = np.sum(cm)-tp1-fn1-fp1

print(tp1, fn1, fp1, tn1)

[13  8  8] [0 0 1] [0 1 0] [17 21 21]
[13  8  8] [0 0 1] [0 1 0] [17 21 21]


In [28]:
precision = tp / (tp + fp) # correct positives out of total
accuracy = (tp + tn)/ (tp + tn + fp + fn) # correct/total
error = 1 - accuracy
recall = tp / (tp + fn)
f1 = (2 * precision * recall) / (precision + recall)

print( "Recall:" , recall ) 
print( "Precision:" , precision ) 
print( "Accuracy:" , accuracy ) 
print( "Error rate:" , error ) 
print( "F1:" , f1 )

Recall: [1.         1.         0.88888889]
Precision: [1.         0.88888889 1.        ]
Accuracy: [1.         0.96666667 0.96666667]
Error rate: [0.         0.03333333 0.03333333]
F1: [1.         0.94117647 0.94117647]


In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.89      1.00      0.94         8
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

